name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: previous_tag
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          echo "previous_tag=$PREV_TAG" >> $GITHUB_OUTPUT

      - name: Generate Changelog
        id: changelog
        run: |
          if [ -z "${{ steps.previous_tag.outputs.previous_tag }}" ]; then
            LOG=$(git log --pretty=format:"- %s (%h)")
          else
            LOG=$(git log --pretty=format:"- %s (%h)" ${{ steps.previous_tag.outputs.previous_tag }}..HEAD)
          fi
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "## Changelog" >> $GITHUB_OUTPUT
          echo "$LOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          make_latest: true